In [1]:
### STEP 1: IMPORT REQUIRED LIBRARIES
import pandas as pd
import numpy as np

In [2]:
###STEP 2: LOAD DATASET
df=pd.read_csv(r"C:\Users\DELL\Downloads\loan_data.csv")
df.head()

,age,income,credit_score,loan_amount,approval_status
0,59,40358,302,191626,0
1,49,23267,662,150271,0
2,35,102745,807,123533,1
3,63,109588,573,479628,0
4,28,58513,805,449164,0


In [3]:
###STEP:3 feature and target separation

x=df[['age','income','credit_score','loan_amount']]
y=df[['approval_status']]
x

,age,income,credit_score,loan_amount
0,59,40358,302,191626
1,49,23267,662,150271
2,35,102745,807,123533
3,63,109588,573,479628
4,28,58513,805,449164
...,...,...,...,...
495,46,24621,629,395411
496,30,35034,406,254474
497,46,131927,525,184436
498,54,147858,517,497049


In [4]:
### STEP:4 TRAIN_SPLIT SPLIT

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y, test_size=0.2, random_state=42)
x_train

,age,income,credit_score,loan_amount
249,62,55547,521,251693
433,49,135359,470,115198
19,64,67295,324,424901
322,49,37100,328,157876
332,41,27239,452,313311
...,...,...,...,...
106,27,92592,464,58947
270,31,57892,717,406927
348,47,44285,595,27431
435,48,48732,663,75326


In [5]:
### STEP:5 TRAIN LOGISTIC REGRESSION MODEL
from sklearn.linear_model import LogisticRegression
log_model=LogisticRegression(max_iter=1000)
log_model.fit(x_train,y_train)

C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,1000
,multi_class,'deprecated'


In [6]:
####STEP:6 PREDICTION & EVALUTION
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
y_pred_log=log_model.predict(x_test)
print("Confusion Matrix:\n", confusion_matrix(y_test,y_pred_log))
print("\n Classification Report:\n",classification_report(y_test,y_pred_log))
print("Accuracy:",accuracy_score(y_test,y_pred_log))

Confusion Matrix:
 [[72  6]
 [ 3 19]]

 Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.92      0.94        78
           1       0.76      0.86      0.81        22

    accuracy                           0.91       100
   macro avg       0.86      0.89      0.87       100
weighted avg       0.92      0.91      0.91       100

Accuracy: 0.91


In [7]:
###STEP:7 FEATURE SCALING (MANDATORY)
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)
x_test

,age,income,credit_score,loan_amount
361,55,112234,847,317213
73,28,141954,439,50648
374,35,43386,595,423219
155,22,29435,623,268579
104,61,102873,569,74274
...,...,...,...,...
347,22,145917,448,210735
86,21,109780,620,490324
75,43,109112,389,407732
438,25,43954,796,225971


In [8]:
x_test_scaled

array([[ 0.92513929,  0.8272248 ,  1.7192903 ,  0.36580029],
       [-1.20524543,  1.61698629, -0.79527866, -1.55462537],
       [-0.65292347, -1.00230073,  0.16617418,  1.12950386],
       [-1.67866426, -1.37302626,  0.33874264,  0.01542428],
       [ 1.39855812,  0.57847119,  0.00593204, -1.38441556],
       [ 1.24075184, -0.14948056,  1.40496918,  0.9737892 ],
       [-1.67866426,  0.38905599, -1.28216824,  0.52110431],
       [-0.7318266 , -0.87185191, -1.01715239,  1.08472167],
       [-1.04743915, -0.00486811,  0.86877433,  1.02071829],
       [-1.04743915, -1.1744698 ,  1.70696398,  0.0695361 ],
       [-0.96853602,  1.19013774, -1.41775774, -1.32948965],
       [-0.49511719,  1.79558612,  0.24629525, -0.99169242],
       [-0.49511719,  0.23203376, -0.00639428, -0.73776095],
       [ 0.45172046, -1.59552535, -1.57799988,  0.52177432],
       [-0.7318266 ,  0.33080709,  1.1153007 ,  0.49913827],
       [ 1.08294557,  1.62931635, -1.02947871, -1.64344051],
       [ 0.21501105, -1.

In [9]:
#### STEP:8 TRAIN KNN WITH DIFFERENT K Values
k=3
from sklearn.neighbors import KNeighborsClassifier
knn3=KNeighborsClassifier(n_neighbors=3)
knn3.fit(x_train_scaled,y_train)

y_pred_knn3=knn3.predict(x_test_scaled)
print("K=3 Accuracy:", accuracy_score(y_test,y_pred_knn3))

K=3 Accuracy: 0.9


C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [10]:
k=5
from sklearn.neighbors import KNeighborsClassifier
knn5=KNeighborsClassifier(n_neighbors=5)
knn5.fit(x_train_scaled,y_train)

y_pred_knn5=knn5.predict(x_test_scaled)
print("K=5 Accuracy:", accuracy_score(y_test,y_pred_knn5))

K=5 Accuracy: 0.9


C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [11]:
k=7
from sklearn.neighbors import KNeighborsClassifier
knn7=KNeighborsClassifier(n_neighbors=7)
knn7.fit(x_train_scaled,y_train)

y_pred_knn7=knn7.predict(x_test_scaled)
print("K=7 Accuracy:", accuracy_score(y_test,y_pred_knn7))


K=7 Accuracy: 0.89


C:\Users\DELL\anaconda3\Lib\site-packages\sklearn\neighbors\_classification.py:239: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [12]:
####### STEP 9: TRAIN DECISION TREE MODEL
from sklearn.tree import DecisionTreeClassifier
dt_model=DecisionTreeClassifier(random_state=42)
dt_model.fit(x_train,y_train)

,criterion,'gini'
,splitter,'best'
,max_depth,None
,min_samples_split,2
,min_samples_leaf,1
,min_weight_fraction_leaf,0.0
,max_features,None
,random_state,42
,max_leaf_nodes,None
,min_impurity_decrease,0.0
,class_weight,None


In [13]:
#### STEP 10:PREDICTION&EVALUATION
y_pred_dt=dt_model.predict(x_test)
print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred_dt))
print("\n Classification Report:\n",classification_report(y_test,y_pred_dt))
print("Accuracy:", accuracy_score(y_test,y_pred_dt))

Confusion Matrix:
 [[75  3]
 [ 3 19]]

 Classification Report:
               precision    recall  f1-score   support

           0       0.96      0.96      0.96        78
           1       0.86      0.86      0.86        22

    accuracy                           0.94       100
   macro avg       0.91      0.91      0.91       100
weighted avg       0.94      0.94      0.94       100

Accuracy: 0.94


In [14]:
results=pd.DataFrame({
    'Model':['Logistic Regression','KNN (Best K)','Decision Tree'],
    'Accuracy':[accuracy_score(y_test,y_pred_log),max(
    accuracy_score(y_test,y_pred_knn3),
    accuracy_score(y_test,y_pred_knn5),
    accuracy_score(y_test,y_pred_knn7)),
               accuracy_score(y_test,y_pred_dt)]
})
results

,Model,Accuracy
0,Logistic Regression,0.91
1,KNN (Best K),0.90
2,Decision Tree,0.94
